### ISSUE TITLE
Plugins menu is only available from the home screen

### ISSUE THREAD

**Issue by xaque208** [OpenSprinkler/OpenSprinklerGen2#16]
At the web interface to configure the OpenSprinkler, the menu for plugins appears only on the home screen. So if I click "log" on top, for example, I do not see the plugins drop down that I see after clicking the home icon.

Running 2.0.3 on a beagle, with a CPU temp of 53C.

**Comment by salbahra** [comment]
Apologies but you have the wrong repository. I believe you are looking for: https://github.com/Dan-in-CA/OSPi

Also, Dan's OSPi is now on 2.2 so I recommend upgrading to make sure the issue is still present.

Thanks

**Comment by xaque208** [comment]
Is the OSPi repo you linked the source for the web interface for the OpenSprinkler project?  I'll read the docs on upgrading.

**Comment by salbahra** [comment]
The upgrading documentation is here: http://rayshobby.net/mediawiki/index.php/Python_Interval_Program_for_OSPi#Updating_the_program

That package has everything contained in one repository.

The official OpenSprinkler app on all stores support this firmware for the OSPi. It also supports the Unified firmware which is this repository hosting the issue we are discussing.

**Comment by xaque208** [comment]
I've upgraded this morning.  Looks much better.  Thanks for the links.  I may consider trying to package the thing for just an `apt-get upgrade` with the right repo in place, and viola.
